services:
  - type: web
    name: nucircle-server
    runtime: node
    rootDir: ./
    buildCommand: npm install --include=dev && npm run build --workspace=shared && npm run build --workspace=server
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
